### PR TITLE
Refactor: ExhangeIssuance to FlashMint.

### PR DESCRIPTION
**Pull request by ElmoArmy**
- [x] Rename instances of ExhangeIssuance to FlashMint in the name of files/contracts/functions. 
- [x] Rename instances of ExhangeIssuance to FlashMint in comments/tests/error strings.
- [x] Pass in _cEtherAddress in as constructor argument.
- [x] Remove unused variables.

### CODE REVIEW

**Comment by ElmoArmy** [comment]
> [Coverage Status](https://coveralls.io/builds/51828280)
> 
> Coverage decreased (-1.3%) to 83.932% when pulling **[96ccb5b](https://github.com/IndexCoop/index-coop-smart-contracts/commit/96ccb5b6428f3171e4844ba153c5ad55dbc38ad0) on Feat/FlashMintLeveragedForCompound** into **[19d09e9](https://github.com/IndexCoop/index-coop-smart-contracts/commit/19d09e999dd93f75652a1993368f927029268103) on master**.

Seems like the reason coverage drops is because of the introductions of the "external" library, Exponential. 
https://coveralls.io/builds/51828280/source?filename=contracts%2Flib%2FExponential.sol

I believe the solution is to exclude this library from being included in coverage ( as well as any other external library) as opposed to testing an external project. Wdyt @ckoopmann ?

**Comment by ckoopmann** [comment]
> > [Coverage Status](https://coveralls.io/builds/51828280)
> > Coverage decreased (-1.3%) to 83.932% when pulling **[96ccb5b](https://github.com/IndexCoop/index-coop-smart-contracts/commit/96ccb5b6428f3171e4844ba153c5ad55dbc38ad0) on Feat/FlashMintLeveragedForCompound** into **[19d09e9](https://github.com/IndexCoop/index-coop-smart-contracts/commit/19d09e999dd93f75652a1993368f927029268103) on master**.
> 
> Seems like the reason coverage drops is because of the introductions of the "external" library, Exponential. https://coveralls.io/builds/51828280/source?filename=contracts%2Flib%2FExponential.sol
> 
> I believe the solution is to exclude this library from being included in coverage ( as well as any other external library) as opposed to testing an external project. Wdyt @ckoopmann ?

Yes agreed, no need to test external libraries (assuming they are well tested in the original codebase).
Maybe move this library (and all external ones) to a subfolder ".../external" and ignore that, to make it more explicit.

**Review by ckoopmann — APPROVED** [review]
LGTM! Feel free to merge.
Remember to add `feat` in front of merged commit (if you squash and merge) to make sure release is triggered.

**Pull request merged**
